
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { ArrowLeft, FileText, Github } from "lucide-react";
import Link from "next/link";
import Image from "next/image";

export default function Adapt() {
    return (
        <main className="min-h-screen bg-white py-20">
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
                <Link href="/publications" className="inline-flex items-center text-sm text-gray-500 hover:text-gray-900 mb-8 transition-colors">
                    <ArrowLeft className="mr-2 h-4 w-4" />
                    Back to Publications
                </Link>

                {/* Title Section */}
                <div className="text-center mb-12">
                    <h1 className="text-3xl md:text-5xl font-bold text-gray-900 mb-6 tracking-tight">
                        Adapting with an Open Mind: Leveraging Open-Vocabulary Detectors for Closed Set Source-Free Domain Adaptive Object Detection
                    </h1>
                    <div className="flex flex-wrap justify-center gap-4 text-lg text-gray-600 mb-6">
                        <span>Kaustubh R Borgavi</span>
                        <span>Sarvesh Shashikumar</span>
                        <span>Chetan Arora</span>
                    </div>
                    <div className="flex justify-center items-center gap-2 mb-8">
                        <Badge variant="outline" className="text-md py-1 px-3">CVPR 2026</Badge>
                    </div>

                    <div className="flex flex-wrap justify-center gap-4">
                        <Button className="gap-2" disabled>
                            <FileText className="h-4 w-4" />
                            Paper
                        </Button>
                        <Button className="gap-2" disabled>
                            <Github className="h-4 w-4" />
                            Code
                        </Button>
                    </div>
                </div>

                {/* Abstract */}
                <section className="mb-16">
                    <h2 className="text-2xl font-bold text-gray-900 mb-4">Abstract</h2>
                    <p className="text-gray-700 leading-relaxed text-lg text-justify">
                        Source-Free Domain Adaptive Object Detection (SFDAOD) aims to adapt a detector trained on a labeled source domain to an unlabeled target domain without accessing source data. We identify a key complementarity: Open-Vocabulary Object Detectors (OVODs) offer strong domain generalization but weaker source-domain accuracy, whereas Closed-Set Object Detectors (CSODs) exhibit the opposite behavior.
                    </p>
                    <p className="text-gray-700 leading-relaxed text-lg text-justify">
                        Existing SFDAOD methods typically employ a Mean-Teacher (MT) framework, where pseudo-labels generated by a source-pretrained teacher model guide a student model, and the teacher is in-turn updated via Exponential Moving Average. We observe that these pseudo-labels frequently carry a source-domain bias, which impedes effective target-domain adaptation. To address this, we propose a <strong>Dual-Branch Distillation framework</strong> that augments the student with two post-decoder projection heads: a main branch distilling from the source-pretrained teacher and an auxiliary branch distilling from an OVOD "anchor" model. The proposed design enables joint learning of domain-invariant features from the OVOD and domain-specific representations from the CSOD.
                    </p>
                    <p className="text-gray-700 leading-relaxed text-lg text-justify">
                        Extensive experiments demonstrate consistent gains over prior state-of-the-art (SOTA), achieving <strong>+14.4%</strong> on Sim10k → Cityscapes, <strong>+11.5%</strong> on Kitti → Cityscapes, <strong>+4.7%</strong> on Cityscapes → Foggy-Cityscapes and <strong>+7.9%</strong> on Cityscapes → BDD100k.
                    </p>
                </section>

                {/* Teaser Image Placeholder */}
                <section className="mb-16">
                    <div className="w-full bg-gray-50 rounded-xl overflow-hidden border border-gray-200 shadow-sm">
                        <Image
                            src="/images/paper-architectures/adapting-with-an-open-mind/adapting-with-an-open-mind.png"
                            alt="Adapting with an Open Mind Architecture"
                            width={1200}
                            height={600}
                            className="w-full h-auto"
                            priority
                        />
                    </div>
                    <p className="mt-4 text-center text-gray-500 italic">
                        Our model architecture consisting of a Mean-Teacher (MT) framework where the student model contains a dual
                        branch decoder, providing two sets of predictions for a given image. The CSOD teacher model is initialized with the same weights as that
                        of the student and its weights are updated indirectly via Exponential Moving Average (EMA). We use GDINO [41] as our OVOD anchor
                        model which distills domain-invariant representations to the student through the auxiliary branch whereas the CSOD teacher preserves the
                        transferable, domain-specific features in the student through the main branch.
                    </p>
                </section>

                {/* Citation */}
                <section>
                    <h2 className="text-2xl font-bold text-gray-900 mb-4">Citation</h2>
                    <Card className="bg-gray-50 border-gray-200">
                        <CardContent className="p-4 overflow-x-auto">
                            <pre className="text-sm text-gray-700 font-mono whitespace-pre">{`@inproceedings{borgavi2026adapting,
                                title={Adapting with an Open Mind: Leveraging Open-Vocabulary Detectors for Closed Set Source-Free Domain Adaptive Object Detection},
                                author={Borgavi, Kaustubh R and Shashikumar, Sarvesh and Arora, Chetan},
                                booktitle={IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR), Findings Track},
                                year={2026}
                                }`}
                            </pre>
                        </CardContent>
                    </Card>
                </section>
            </div>
        </main>
    );
}
